# Generated by Django 5.0.1 on 2024-02-19 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_count', models.CharField(blank=True, default=0, max_length=5, null=True, verbose_name='Количество калорий')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рецепта')),
                ('description', models.TextField(verbose_name='Описание рецепта')),
                ('preview_image', models.ImageField(max_length=255, upload_to='images/', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_minutes', models.IntegerField(default=1, help_text='В минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления')),
                ('category', models.CharField(choices=[('B', 'Завтрак'), ('D', 'Обед'), ('S', 'Ужин')], max_length=1, verbose_name='Прием пищи')),
                ('ingredients', models.ManyToManyField(to='app.ingredient', verbose_name='Ингредиенты')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
