# Generated by Django 5.0.1 on 2024-02-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview_image',
            field=models.CharField(max_length=255, verbose_name='Картинка'),
        ),
    ]
